app/models.py
from app import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.Text, nullable=False)


    def __init__(self, id, username, password):
        self.id = id
        self.username = username
        self.password = password


    def __repr__(self):
        return f"<User: {self.username}>"
    


class Registro(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    id_producto = db.Column(db.String, nullable=False)
    nombre_producto = db.Column(db.String, nullable=False)
    proveedor = db.Column(db.String, nullable=False)
    categoria = db.Column(db.String, nullable=False)
    lote = db.Column(db.String, nullable=False)
    cantidad = db.Column(db.Integer, nullable=False)
    descripcion = db.Column(db.Text, nullable=False)
    registrado_por = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)


    def __init__(self, id, id_producto, nombre_producto, proveedor, categoria, lote, cantidad, descripcion, registrado_por):
        self.id = id
        self.id_producto = id_producto
        self.nombre_producto = nombre_producto
        self.proveedor = proveedor
        self.categoria = categoria
        self.lote = lote
        self.cantidad = cantidad
        self.descripcion = descripcion
        self.registrado_por = registrado_por

    def __repr__(self):
        return f"<User: {self.nombre_producto}>"

app/models/models.py
from app import db


# Modelo para signup
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.Text, nullable=False)


    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password


    def __repr__(self):
        return f"<User: {self.username}>"
    

# Modelo para nuevos registros
class Registro(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True) 
    id_producto = db.Column(db.String, nullable=False)
    nombre_producto = db.Column(db.String, nullable=False)
    proveedor = db.Column(db.String, nullable=False)
    categoria = db.Column(db.String, nullable=False)
    lote = db.Column(db.String, nullable=False)   
    cantidad = db.Column(db.Integer, nullable=False)
    descripcion = db.Column(db.Text, nullable=False)
    #registrado_por = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)


    def __init__(self, id_producto, nombre_producto, proveedor, categoria, lote, cantidad, descripcion):
        self.id_producto = id_producto
        self.nombre_producto = nombre_producto
        self.proveedor = proveedor
        self.categoria = categoria
        self.lote = lote
        self.cantidad = cantidad
        self.descripcion = descripcion
        #self.registrado_por = registrado_por

    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def create_app():
    app = Flask(__name__, template_folder='templates')
    app.config.from_mapping(
        DEBUG = True,
        SECRETE_KEY = 'dev',
        SQLALCHEMY_DATABASE_URI = "sqlite:///inventario.db"
    )


    app.config['SECRET_KEY'] = 'dev'


    db.init_app(app)


    from app.auth.auth_blueprint import auth_bp
    from .main import main_bp


    app.register_blueprint(auth_bp)
    app.register_blueprint(main_bp)


    with app.app_context():
        db.create_all()


    return app

app/main/__init__.py
from flask import Blueprint


main_bp = Blueprint('main', __name__, url_prefix='/main')


from . import routes

app/main/routes.py
from flask import render_template, request, flash
from sqlalchemy import func
from app.main import  main_bp
from app.models.models import Registro
from productos import productos
from app import db
import csv
from io import StringIO
import pandas as pd
from app.auth.auth_blueprint import login_required


# ENDPOINT A LA PÁGINA PARA VER LOS REGISTROS REALIZADOS
@main_bp.route('/historial')
@login_required
def historial():
    inventario = db.session.query(Registro).order_by(Registro.id.desc()).all()
    return render_template('main/historial.html', productos=inventario) 


# ENDPOINT A LA PÁGINA PARA INGRESAR MATERIALES
@main_bp.route('/nuevo-registro', methods=['GET', 'POST'])
@login_required
def nuevo_registro():
    if request.method == 'POST':
        if 'submitFormulario' in request.form:
            id_producto = request.form['idProducto']
            nombre = request.form['nombreProducto']
            proveedor = request.form['proveedorProducto']
            categoria = request.form['categoriaProducto']
            lote = request.form['loteProducto']
            cantidad = request.form['cantidadProducto']
            descripcion = request.form['descripcionProducto']

            new_register = Registro(id_producto=id_producto, nombre_producto=nombre, proveedor=proveedor, 
                                    categoria=categoria, lote=lote, cantidad=cantidad, descripcion=descripcion)
            db.session.add(new_register)
            db.session.commit()
        
        flash('Registrado exitosamente!.', 'success')
    
    return render_template('main/nuevo_registro.html')    


##########################

# ENDPOINT DE LA PÁGINA INVENTARIO
@main_bp.route('/inventario')
@login_required
def inventario():
    # Realiza la consulta para sumar los valores por nombre
    inventario = db.session.query(Registro.nombre_producto, func.sum(Registro.cantidad)).group_by(Registro.nombre_producto).all()

    return render_template('/main/inventario.html', inventario=inventario)


@main_bp.route('/subir-csv', methods=['GET', 'POST'])
@login_required  
def upload_csv():
    if request.method == 'POST':
        if 'submitCSV' in request.form:
            uploaded_file = request.files['csv_file']

            if uploaded_file.filename != '':
                try:
                    data = pd.read_csv(uploaded_file, header=0)
                    for _, row in data.iterrows():
                        #id_producto, producto, proveedor, categoria, lote, cantidad, descripcion = row

                        new_register = Registro(id_producto=row['id_producto'], 
                                                nombre_producto=row['producto'], 
                                                proveedor=row['proveedor'], 
                                                categoria=row['categoria'], 
                                                lote=row['lote'], 
                                                cantidad=row['cantidad'], 
                                                descripcion=row['descripcion'])
                        db.session.add(new_register)
                    db.session.commit()
                
                except Exception as e:
                    return f"Error al cargar archivo: {str(e)}"
                    


                # Puedes realizar más procesamiento con los datos del CSV aquí

    return render_template('main/nuevo_registro.html')

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</head>
<body>
    <div class="container">
        <nav id="navbar" class="navbar navbar-expand-lg fixed-top mb-5">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">MyApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                    <div>
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <!-- Página para consultar el inventario-->
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.inventario') }}">INVENTARIO</a>
                            </li>
                            <!-- Página para REGISTRAR -->
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{{ url_for('main.nuevo_registro') }}">REGISTRAR</a>
                            </li>
                            <!-- Página para ver los registros-->
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.historial') }}">HISTORIAL</a>
                            </li>
                        </ul>
                    </div>
                    <div class="ml-auto"> <!-- Agrupamos los dos últimos div y aplicamos ml-auto -->
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item me-5">
                                <form class="d-flex">
                                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                    <button class="btn" type="submit">Buscar</button>
                                </form>
                            </li>
                            <li class="nav-item me-5">
                                <div class="dropdown-center">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ g.user.username }}
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Cambiar Contraseña</a></li>   
                                        <li><a class="dropdown-item" href="{{ url_for('auth.logout')}}">Cerrar Sesión</a></li>                            
                                    </ul>
                                  </div>
                            </li>
                
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>


    {% block content %}
    <!-- Bloque de contenido -->
    {% endblock %}


</body>
</html>

app/templates/main/historial.html
{% extends 'main/base.html' %}

{% block title %}Registros{% endblock %}

{% block content %}

<body  style="margin-top: 100px;">
    <h1 class="text-center mb-3">HISTORIAL DEL REGISTRO DE MATERIALES</h1>
    <div class="container-lg">
        
        <div class="card">
            <div id="card-header" class="card-header text-center">REGISTROS</div>
            <div class="card-body">

                <!-- Tabla -->
                <table class="table table-responsive table-bordered">
                    <thead>
                        <th scope="col"></th>
                        <th scope="col">ID Producto</th>
                        <th scope="col">Producto</th>
                        <th scope="col">Proveedor</th> 
                        <th scope="col">Categoría</th>
                        <th scope="col">Lote</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Descripción</th>
                    </thead>
                
                    <tbody>
                        {% for p in productos %}
                        
                        <tr>
                            <td> {{ p['id'] }} </td>
                            <td> {{ p['id_producto'] }}</td>
                            <td> {{ p['nombre_producto'] }} </td>
                            <td> {{ p['proveedor'] }} </td>
                            <td> {{ p['categoria'] }} </td>
                            <td> {{ p['lote'] }} </td>
                            <td> {{ p['cantidad'] }} </td>
                            <td> {{ p['descripcion'] }} </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
            </div>
        </div>
                
    </div>
</body>

{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<body style="margin-top: 120px;">
    
    <h1 class="text-center mt-5 mb-5">AGREGAR NUEVO REGISTRO</h1>

    <!-- Formas para la introducción de datos -->
    <div class="container">
        <div class="card shadow">
        <div id="card-header" class="card-header text-center"> Introduce la información</div>
            <div class="card-body">
                
                <form action="{{ url_for('home') }}" method="POST">
                    <div class="row mb-3">
                        <div class="row">
                            <div class="col">
                                <label>ID del Producto</label>
                                <input type="text" class="form-control mb-3" name="idProducto">
                            </div>
                            <div class="col">
                                <label>Nombre del Producto</label>
                                <input type="text" class="form-control mb-3" name="nombreProducto">
                            </div>
                        
                            <div class="col">
                                <label>Proveedor</label>
                                <input type="text" class="form-control mb-3" name="proveedorProducto">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label>Categoría</label>
                                <input type="text" class="form-control mb-3" name="categoriaProducto">
                            </div>
                            <div class="col">
                                <label>Lote</label>
                                <input type="text" class="form-control mb-3" name="loteProducto">
                            </div>
                            <div class="col">
                                <label>Cantidad de Inventario</label>
                                <input type="text" class="form-control mb-3" name="cantidadProducto">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label>Descripción</label>
                                <input type="text" class="form-control mb-3" name="descripcionProducto">
                            </div>
                        </div>
                        <div class="col">
                            <button class="btn-lg" type="submit" id="btn-submit">Guardar Registro</button>
                        </div>
                    </div>
                </form>
            
    </div>
 
</body>
{% endblock %}

app/templates/main/inventario.html
{% extends 'main/base.html' %}

{% block title %}Registros{% endblock %}

{% block content %}


<body  style="margin-top: 120px;">
    <h1 class="text-center mb-3">INVENTARIO DE MATERIALES</h1>
    <div class="container-lg d-flex justify-content-center">

        <div class="card col-md-9">
            <div id="card-header" class="card-header text-center">Inventario de Materiales</div>
            <div class="card-body">


                <!-- Tabla -->
                <table class="table table-responsive table-bordered">
                    <thead>
                        <th scope="col">Producto</th>
                        <th scope="col">Cantidad</th>
                    
                    </thead>
                
                    <tbody>
                        
                        {% for i in inventario %}
                        
                        <tr>
                            <td> {{ i[0] }} </td>
                            <td> {{ i[1] }}</td>
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            
            </div>
        </div>

                        

{% endblock %}

app/templates/main/nuevo_registro.html
{% extends 'main/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<body style="margin-top: 120px;">
    
    <h1 class="text-center mt-5 mb-5">AGREGAR NUEVO REGISTRO</h1>

    <!-- Formas para la introducción de datos -->
    <div class="container">
        <div class="card shadow">
            <div id="card-header" class="card-header text-center"> 
                Introduce la información
            </div>
            <div class="card-body">
                
                <form action="{{ url_for('main.nuevo_registro') }}" method="POST">
                    <div class="row mb-3">
                        <div class="row">
                            <div class="col">
                                <label>ID del Producto</label>
                                <input type="text" class="form-control mb-3" name="idProducto">
                            </div>
                            <div class="col">
                                <label>Nombre del Producto</label>
                                <input type="text" class="form-control mb-3" name="nombreProducto">
                            </div>
                        
                            <div class="col">
                                <label>Proveedor</label>
                                <input type="text" class="form-control mb-3" name="proveedorProducto">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label>Categoría</label>
                                <input type="text" class="form-control mb-3" name="categoriaProducto">
                            </div>
                            <div class="col">
                                <label>Lote</label>
                                <input type="text" class="form-control mb-3" name="loteProducto">
                            </div>
                            <div class="col">
                                <label>Cantidad de Inventario</label>
                                <input type="text" class="form-control mb-3" name="cantidadProducto">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label>Descripción</label>
                                <input type="text" class="form-control mb-3" name="descripcionProducto">
                            </div>
                        </div>
                        <div class="col d-flex justify-content-center align-items-center mt-3">
                            <button class="btn-lg" name="submitFormulario" type="submit" id="btn-submit">Guardar Registro</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="container mt-3">
                <div class="row">
                    <div class="col-md-6 mx-auto">
                    <div class="alert alert-success text-center" role="alert" id="flash-message">
                        {{ messages[0] }}  <!-- Muestra el primer mensaje flash -->
                    </div>
                    </div>
                </div>
                </div>
                <script>
                document.addEventListener("DOMContentLoaded", function() {
                    setTimeout(function () {
                    var flashMessage = document.getElementById('flash-message');
                    if (flashMessage) {
                        flashMessage.style.display = 'none';
                    }
                    }, 1000);  // Oculta el mensaje después de 1 segundo (1000 milisegundos)
                });
                </script>
            {% endif %}
        {% endwith %}
            
    </div>

    <div class="container mt-5">
        <div class="card shadow">
            <div id="card-header" class="card-header text-center"> 
                Carga un archivo .csv
            </div>
            <div class="card-body">
                <form action="{{ url_for('main.upload_csv') }}" method="POST" enctype="multipart/form-data">
                    <div class="text-center">
                        <label for="">Selecciona un archivo:</label>
                        <input type="file" name="csv_file" id="csv_file">
                        
                    </div>
                    <div class="col d-flex justify-content-center align-items-center mt-3" >
                        <button class="btn-lg" name="submitCSV" type="submit" id="btn-submit">Subir Registros</button>
                    </div>
                </form>
            </div>


    </div>
 
</body>
{% endblock %}

app/templates/main/registro.html
{% extends 'main/base.html' %}

{% block title %}Registros{% endblock %}

{% block content %}

<body  style="margin-top: 120px;">
    <h1 class="text-center mb-3">REGISTROS ALMACENADOS</h1>
    <div class="container-lg">
        
        <div class="card">
            <div id="card-header" class="card-header text-center">Información de Registros</div>
            <div class="card-body">

                <!-- Tabla -->
                <table class="table table-responsive table-bordered">
                    <thead>
                        <th scope="col"></th>
                        <th scope="col">ID Producto</th>
                        <th scope="col">Producto</th>
                        <th scope="col">Proveedor</th>
                        <th scope="col">Categoría</th>
                        <th scope="col">Lote</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Descripción</th>
                    </thead>
                
                    <tbody>
                        {% for p in productos %}
                        
                        <tr>
                            <td> {{ p['id'] }} </td>
                            <td> {{ p['id_producto'] }}</td>
                            <td> {{ p['nombre_producto'] }} </td>
                            <td> {{ p['proveedor'] }} </td>
                            <td> {{ p['categoria'] }} </td>
                            <td> {{ p['lote'] }} </td>
                            <td> {{ p['cantidad'] }} </td>
                            <td> {{ p['descripcion'] }} </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
            </div>
        </div>
                
    </div>
</body>

{% endblock %}